site_name: "PHongo: CRUD - The Create Read Update and Delete interface for PHongo"
repo_url: https://github.com/bjori/phongo-crud
theme: spacelab
pages:
    - [index.md, Home]
extra_javascript:
    - pretty.js
