site_name: "PHongo libraries"
repo_url: https://github.com/10gen-labs/mongo-php-library-prototype
theme: spacelab
pages:
    - [index.md, Home]
    - [usage.md, Usage]
    - [data.md, Example data]
extra_javascript:
    - pretty.js
